"""Add cv_gcs_uri column to resumes table

Revision ID: 8766e3dc881e
Revises: 
Create Date: 2025-04-26 15:23:35.528284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8766e3dc881e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First check if the column exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('resumes')]
    
    # Add the column if it doesn't exist
    if 'cv_gcs_uri' not in columns:
        op.add_column('resumes', sa.Column('cv_gcs_uri', sa.String(), nullable=True))
    else:
        # If it exists, just alter the type if needed
        op.alter_column('resumes', 'cv_gcs_uri',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'cv_gcs_uri')
    # ### end Alembic commands ###
