"""add feedback_total and test justi

Revision ID: 8fd914250144
Revises: 57c2d53f5d02
Create Date: 2025-05-06 01:38:40.875440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd914250144'
down_revision: Union[str, None] = '57c2d53f5d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    op.create_index(op.f('ix_feedback_skills_justification'), 'feedback_skills', ['justification'], unique=False)
    op.add_column('test_skills', sa.Column('justification', sa.String(), nullable=True))
    op.create_index(op.f('ix_test_skills_justification'), 'test_skills', ['justification'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_skills_justification'), table_name='test_skills')
    op.drop_column('test_skills', 'justification')
    op.drop_index(op.f('ix_feedback_skills_justification'), table_name='feedback_skills')
    op.drop_table('feedback_skills')
    # ### end Alembic commands ###
