"""add user_type, is_active, expires_at to users

Revision ID: ae542874ecaf
Revises: 8fd914250144
Create Date: 2025-05-07 22:17:33.792817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae542874ecaf'
down_revision: Union[str, None] = '8fd914250144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_type_enum = sa.Enum('individual', 'company', name='usertype')
    user_type_enum.create(op.get_bind())  # Важно: это создаёт ENUM в PostgreSQL

    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.add_column('users', sa.Column('user_type', sa.Enum('individual', 'company', name='usertype'), nullable=True,server_default='individual'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True,server_default=sa.text("TRUE")))
    op.add_column('users', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_column('users', 'expires_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'user_type')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.execute('DROP TYPE usertype')  # удаляем enum тип

    # ### end Alembic commands ###
