"""empty message

Revision ID: b4eeecceab16
Revises: ae542874ecaf
Create Date: 2025-05-07 23:28:00.900115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4eeecceab16'
down_revision: Union[str, None] = 'ae542874ecaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=postgresql.ENUM('individual', 'company', name='usertype'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'individual'::usertype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('individual', 'company', name='usertype'),
               existing_nullable=True,
               existing_server_default=sa.text("'individual'::usertype"))
    # ### end Alembic commands ###
