services:
  fastapi:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ../.env  
    depends_on:
      - postgres_db
    volumes:
      - static_volume:/app/back_static/
      - media_volume:/app/back_media/
      - ../:/app/

  postgres_db:
    image: postgres:14.3-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - ../.env  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - fastapi
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
